"""initial schema

Revision ID: 74f2a0f415d5
Revises: 
Create Date: 2026-09-11 02:14:06.028531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f2a0f415d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_role',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('approval_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='Sample_test'
    )
    op.create_table('approval_band',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('international_only', sa.Boolean(), nullable=False),
    sa.Column('required_levels', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    schema='Sample_test'
    )
    op.create_table('city_tier',
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('city'),
    schema='Sample_test'
    )
    op.create_table('permission',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    schema='Sample_test'
    )
    op.create_table('policy_config',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    schema='Sample_test'
    )
    op.create_table('employee',
    sa.Column('emp_code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=128), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('cost_centre', sa.String(length=16), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('reporting_manager_code', sa.String(length=16), nullable=True),
    sa.Column('role_code', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporting_manager_code'], ['Sample_test.employee.emp_code'], ),
    sa.ForeignKeyConstraint(['role_code'], ['Sample_test.app_role.code'], ),
    sa.PrimaryKeyConstraint('emp_code'),
    sa.UniqueConstraint('email'),
    schema='Sample_test'
    )
    op.create_table('role_permission',
    sa.Column('role_code', sa.String(length=32), nullable=False),
    sa.Column('permission_code', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['permission_code'], ['Sample_test.permission.code'], ),
    sa.ForeignKeyConstraint(['role_code'], ['Sample_test.app_role.code'], ),
    sa.PrimaryKeyConstraint('role_code', 'permission_code'),
    schema='Sample_test'
    )
    op.create_table('travel_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('travel_request_no', sa.String(length=32), nullable=False),
    sa.Column('employee_code', sa.String(length=16), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('visiting_place', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('mode_of_travel', sa.String(length=64), nullable=False),
    sa.Column('is_international', sa.Boolean(), nullable=False),
    sa.Column('estimated_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('advance_requested', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_code'], ['Sample_test.employee.emp_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('travel_request_no'),
    schema='Sample_test'
    )
    op.create_table('advance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('travel_request_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('disbursed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['travel_request_id'], ['Sample_test.travel_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('travel_request_id'),
    schema='Sample_test'
    )
    op.create_table('claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('travel_request_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('submission_no', sa.Integer(), nullable=False),
    sa.Column('cycle_no', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('total_employee_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_company_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_disallowed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_reimbursable', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('advance_drawn', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_payable', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_recoverable', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_code'], ['Sample_test.employee.emp_code'], ),
    sa.ForeignKeyConstraint(['travel_request_id'], ['Sample_test.travel_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='Sample_test'
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=16), nullable=False),
    sa.Column('travel_request_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('image_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('doc_type', sa.String(length=48), nullable=True),
    sa.Column('extraction_mode', sa.String(length=24), nullable=True),
    sa.Column('extraction_raw_json', sa.Text(), nullable=True),
    sa.Column('discarded', sa.Boolean(), nullable=False),
    sa.Column('discard_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_code'], ['Sample_test.employee.emp_code'], ),
    sa.ForeignKeyConstraint(['travel_request_id'], ['Sample_test.travel_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='Sample_test'
    )
    op.create_table('estimate_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('travel_request_id', sa.Integer(), nullable=False),
    sa.Column('head', sa.String(length=64), nullable=False),
    sa.Column('basis', sa.String(length=128), nullable=False),
    sa.Column('estimate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('borne_by', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['travel_request_id'], ['Sample_test.travel_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='Sample_test'
    )
    op.create_table('approval_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('cycle_no', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=24), nullable=False),
    sa.Column('role_code', sa.String(length=32), nullable=False),
    sa.Column('assigned_to_code', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('skip_reason', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_code'], ['Sample_test.employee.emp_code'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['Sample_test.claim.id'], ),
    sa.ForeignKeyConstraint(['role_code'], ['Sample_test.app_role.code'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='Sample_test'
    )
    op.create_table('claim_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('actor_code', sa.String(length=16), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_code'], ['Sample_test.employee.emp_code'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['Sample_test.claim.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='Sample_test'
    )
    op.create_table('claim_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=16), nullable=False),
    sa.Column('head', sa.String(length=64), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('merchant', sa.String(length=128), nullable=True),
    sa.Column('from_place', sa.String(length=128), nullable=True),
    sa.Column('to_place', sa.String(length=128), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('disallowed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('disallowed_reason', sa.String(length=255), nullable=True),
    sa.Column('paid_by', sa.String(length=16), nullable=False),
    sa.Column('proof_document_id', sa.Integer(), nullable=True),
    sa.Column('proof_ref', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_line_id', sa.Integer(), nullable=True),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['Sample_test.claim.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_line_id'], ['Sample_test.claim_line.id'], ),
    sa.ForeignKeyConstraint(['proof_document_id'], ['Sample_test.document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='Sample_test'
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('scheduled_run_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['Sample_test.claim.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id'),
    schema='Sample_test'
    )
    op.create_table('line_policy_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_line_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('policy_ref', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['claim_line_id'], ['Sample_test.claim_line.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='Sample_test'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('line_policy_flag', schema='Sample_test')
    op.drop_table('payment', schema='Sample_test')
    op.drop_table('claim_line', schema='Sample_test')
    op.drop_table('claim_event', schema='Sample_test')
    op.drop_table('approval_step', schema='Sample_test')
    op.drop_table('estimate_line', schema='Sample_test')
    op.drop_table('document', schema='Sample_test')
    op.drop_table('claim', schema='Sample_test')
    op.drop_table('advance', schema='Sample_test')
    op.drop_table('travel_request', schema='Sample_test')
    op.drop_table('role_permission', schema='Sample_test')
    op.drop_table('employee', schema='Sample_test')
    op.drop_table('policy_config', schema='Sample_test')
    op.drop_table('permission', schema='Sample_test')
    op.drop_table('city_tier', schema='Sample_test')
    op.drop_table('approval_band', schema='Sample_test')
    op.drop_table('app_role', schema='Sample_test')
    # ### end Alembic commands ###
